Daniel
DependableSystemsLab/TensorFI pull request #27
Opened 2020-05-29 05:46 UTC by Daniel-Kong

Auto config

2020-06-04 10:01 UTC, zitaoc commented
Hi Daniel,

1. For the multi-bit flip, there are corner cases that are not considered in your current code. E.g., randomBitFlip() is called multiple times (for multi-bit flips), what if they repeatedly flip the same bit?

2. For the Auto config, I tired your code in one of the model I have, where the config file has no entries in the "Instance" section - Ideally, the auto config needs to fill these entries automatically. But i got an error: 

...
    for i in range(len(instances)):
TypeError: object of type 'NoneType' has no len()
...

2020-06-05 20:40 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +	"Flip ont bit of a random element in a tensor"
Change the description of the function as we flip multiple bits

2020-06-05 20:40 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +		randomBitFlip(val)
You need to choose the bit positions that are to be flipped in advance before you call `randomBitFlip`, else you risk repetition

2020-06-05 20:40 UTC, nniranjhana commented on confFiles/default.yaml
> +BitCount: 0
Did you test with different values of BitCount (> 0) and see the results for any model?

2020-06-19 22:01 UTC, nniranjhana requested changes
Also, when you submit PRs, try to have the description included with your sign (`git commit -s`) and a better title. When you address review comments, work the new fixes into your existing commits (`git commit --amend`) so that it's easier for reviewers to apply one or two corresponding patches for every feature associated with the PR for individual testing.

2020-06-19 22:01 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +	list = np.random.sample(range(intLength + decLength), fiConf.bitCount)
Have you tested your code? You'd get a `TypeError` because the random function from the numpy package takes only 1 argument. You should include random package and just have `random.sample()` for this to work.

2020-06-19 22:01 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +	list = np.random.sample(range(intLength + decLength), fiConf.bitCount)
And insert a check to only allow `bitCount` that is lesser than the total number of bits else throw an error, don't trust the user.

2020-06-19 22:01 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +	list = np.random.sample(range(len(val)), fiConf.bitCount)
Same comments as above

2020-06-22 02:34 UTC, zitaoc commented
Hi Daniel,

please note that when we inject multi-bit flips, these multi-bit flips could occur:

1) in the same value - in which case the bit-flips would arise at the different bits of the same value. You can't simply call the same injection function again as you might accidentally inject the same bits for multiple times (same issue we've mentioned earlier).

2) or into different values. 

Please remember to also account the former case.

2020-06-26 03:00 UTC, nniranjhana commented on TensorFI/faultTypes.py
> +		# flip the sign bit (optional)
We consider sign bit also now, there's no reason not to, check recent commit by Zitao and update this as well

2020-08-19 23:11 UTC, closed without merging